#ifndef __ENUMLIST_TABLE_H__
#define __ENUMLIST_TABLE_H__


S_ENUM_LIST T_ENUMLIST[8] = 
{
	{ E_CHAR_KIND_UNDEFINE,"E_CHAR_KIND_UNDEFINE"},
	{ E_CHAR_KIND_STRING,"E_CHAR_KIND_STRING"},
	{ E_CHAR_KIND_NUMBER,"E_CHAR_KIND_NUMBER"},
	{ E_CHAR_KIND_OPERATOR_SINGLE,"E_CHAR_KIND_OPERATOR_SINGLE"},
	{ E_CHAR_KIND_OPERATOR_MULTI,"E_CHAR_KIND_OPERATOR_MULTI"},
	{ E_CHAR_KIND_PERIOD,"E_CHAR_KIND_PERIOD"},
	{ E_CHAR_KIND_SKIP,"E_CHAR_KIND_SKIP"},
	{ E_CHAR_KIND_INVALID,"E_CHAR_KIND_INVALID"},
};
#endif /* __ENUMLIST_TABLE_H__ */
